### ISSUE TITLE
Cannot create any new RPG Manager pages from command palette

### ISSUE THREAD

**Issue by miethaman** [carlonicora/obsidian-rpg-manager#53]
Can't create new RPG Manager pages via command palette since updating from 1.2.5

**Comment by carlonicora** [comment]
@miethaman have you installed the latest version? There was a bug that was fixed in 1.3.2

**Comment by miethaman** [comment]
updated to the most current (1.3.4?) and problem still persists

**Comment by miethaman** [comment]
RPG Manager is the only installed community plugin if that matters

**Comment by carlonicora** [comment]
@miethaman Do you have existing note with RPG Manager elements?

Also, a few more questions:
- if you open the inspector window, is there any issue reported there?
- Are you trying to create a new Campaign or you do have a campaign already set (you need a campaign to create anything else)
- Are you using the "create" or the 'fill"?

Let me know and I will debug the issue quickly
Thanks

**Comment by miethaman** [comment]
![image](https://user-images.githubusercontent.com/12991348/191310233-2961e513-974f-4703-a630-0603e9f73fd1.png)
this error pops up when creating a new file

I have multiple campaigns set up and i am choosing the one i want when using the plugin

I am using create

**Comment by carlonicora** [comment]
@miethaman thanks a lot for this. Can you confirm what type of element are you trying to create? A campaign or something else?
Also, are you on Windows, Mac or Linux?

**Comment by miethaman** [comment]
this happens on all except 'Create a New Campaign'

Windows 11

**Comment by carlonicora** [comment]
@miethaman I think it tries to create a folder that already exists. It does not do this on Mac (my testing platform). Can you please try and replace the files in the plugin folder with these?

I am trying to reproduce the issue on Mac, but I may have some path separator wrong here....


[WinTesting.zip](https://github.com/carlonicora/obsidian-rpg-manager/files/9609549/WinTesting.zip)

**Comment by miethaman** [comment]
![image](https://user-images.githubusercontent.com/12991348/191313086-34d93cdb-2c4b-4ad9-b91d-e36cb01f18dc.png)

Above error when creating a NPC named test to a test campaign

Below error trying to create NPC named test on one of the established campaigns

**Comment by carlonicora** [comment]
@miethaman Sorry for the back and forth, but not having a win machine to test to I am banging my head...

If you go in the settings and remove the option to automatically move new elements in folders, do you still have the same issue?

**Comment by miethaman** [comment]
Well with that it now works, but the auto move is one of the key points of why i want to use this plugin 🙃

**Comment by carlonicora** [comment]
@miethaman let me create a version with some tests that will allow me to try and fix this and I will come back to you asap

**Comment by miethaman** [comment]
👍

**Comment by carlonicora** [comment]
@miethaman Ok, let's try this.

Can you please create a folder called "RPGMTEST" in the root of your vault, and another called "RPGMTEST" inside the newly created folder?

- RPGMTEST
  - RPGMTEST

Then copy the file I am sending in your plugin folder and reload/reactivate the plugin with the inspector open.

When you have done, you can remove the two silly folders! :)

[main.js.zip](https://github.com/carlonicora/obsidian-rpg-manager/files/9609882/main.js.zip)

**Comment by carlonicora** [comment]
@miethaman Can you use THIS file instead and do as I asked before as well as trying to create an NON-PLAYER CHARACTER and see if anything changes?

[main.js.zip](https://github.com/carlonicora/obsidian-rpg-manager/files/9610047/main.js.zip)

**Comment by miethaman** [comment]
Auto move off
create folders and create NPC
[obsidian.md-1663696632453.txt](https://github.com/carlonicora/obsidian-rpg-manager/files/9610186/obsidian.md-1663696632453.txt)

Auto move on
create npc
[obsidian.md-1663696792224.log](https://github.com/carlonicora/obsidian-rpg-manager/files/9610198/obsidian.md-1663696792224.log)

in both cases it now works but spews out many errors

**Comment by carlonicora** [comment]
@miethaman I have released [v1.3.5](https://github.com/carlonicora/obsidian-rpg-manager/releases/tag/1.3.5)

Can you try to update to the latest official version and do another round of tests? It should be ok, even the other issue!

**Comment by miethaman** [comment]
updating and reloading the plugin
[obsidian.md-1663701166416.log](https://github.com/carlonicora/obsidian-rpg-manager/files/9610640/obsidian.md-1663701166416.log)

creating a test NPC
[obsidian.md-1663701212013.log](https://github.com/carlonicora/obsidian-rpg-manager/files/9610646/obsidian.md-1663701212013.log)

it seems to function normally now, but still gives errors (but i can of course only see those with the inspector open)

**Comment by carlonicora** [comment]
@miethaman could you copy/paste the frontmatter of your campaigns please? I don't understand the error you are getting... :S

**Comment by miethaman** [comment]
---
alias: []
tags:
  - rpgm/outline/campaign/2
completed: false
synopsis: ""
settings: Agnostic
dates:
  current: 

---

only thing different in the frontmatter between the campaigns is the number after campaign/

i dont think i touched the fontmatter at all for any of them so that is how it generated them for me in 1.2.5

**Comment by carlonicora** [comment]
@miethaman that's a strange error in a line which I don't see how it can trigger the error.
I am happy the automatic move and creations are sorted out on Windows as well and thanks for using RPG Manager! Happy to help any time and thanks for the support!
